apiVersion: apps/v1
kind: Deployment
metadata:
  name: retry-order-service 
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: retry-order-service
  template:
    metadata:
      labels:
        app: retry-order-service
    spec:
      containers:
        - name: retry-order-service  
          image: retry-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: retry-order-service 
  namespace: default
spec:
  selector:
    app: retry-order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
